name: Build Tweak

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          export THEOS=$HOME/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          echo "THEOS=$THEOS" >> $GITHUB_ENV
          echo "$THEOS/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          brew update
          brew install ldid xz dpkg fakeroot
          # 强制覆盖冲突的 openssl
          brew link --overwrite --force openssl@3 || true

      - name: Build package
        run: |
          make package
          
      - name: Upload deb file
        uses: actions/upload-artifact@v4
        with:
          name: WCClown-Deb
          path: ./packages/*.deb
